apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: insultgenerator-app-prod
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/sa-ne/demo-gitops-quarkus.git'
    path: k8s/environments/prod
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
